---
- name: Configure metricbeat
  hosts: webservers
  become: true
  tasks:
    # Download Deb
    - name: download Deb
      command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: install deb
      command: sudo  dpkg -i  metricbeat-7.4.0-amd64.deb

    - name: copy deb to VM
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: metricbeat enable
      command: metricbeat modules enable docker

    - name: metricbeat setup
      command: metricbeat setup

    - name: metricbeat start
      command: service metricbeat start